### ISSUE TITLE
Remove model jepsen-set OR jepsen-set-full

### ISSUE THREAD

**Issue by ligurio** [ligurio/elle-cli#41]
`jepsen-set-full` and `jepsen-set` uses the same history format, see - [set-full](https://github.com/jepsen-io/jepsen/blob/fe76b06cc68f50abec010c0e83138b819f7c6877/jepsen/src/jepsen/checker.clj#L461-L532)
and [set](https://github.com/jepsen-io/jepsen/blob/main/jepsen/src/jepsen/checker.clj#L240-L243).

Need to understand a difference and probably leave a single one.

**Comment by aphyr** [comment]
Just if you're wondering "why both?"--they use the same kinds of histories, but have different computational complexities! The `set-full` checker is a lot more expensive, but gives you precise bounds on latencies and stability of records over time, whereas `set` assumes a single read at the end of the test.

**Comment by ligurio** [comment]
@aphyr Heh, thanks for explanation, Kyle :)
Seems both are useful.
