### ISSUE TITLE
Exit with non-zero exit code if any history fails verification

### ISSUE THREAD

**Issue by mprimi** [ligurio/elle-cli#53]
Elle-cli currently exits with code 0 if any analysis is performed.

This makes it a little hard to script around it.
e.g., one has to parse the output and look for the `'{"valid?":true}'` string.

Suggestion: exit with a non-zero exit code if any of the analyses was invalid.

**Comment by ligurio** [comment]
It seems so.

https://github.com/ligurio/elle-cli/blob/6b71c436f9b454946bdec4e55b8b6820ed9abe89/src/elle_cli/cli.clj#L232

**Comment by mprimi** [comment]
Right. I was making a suggestion to change to something like:

`(System/exit (if all-valid 0 100))`

**Comment by mprimi** [comment]
Thank you @ligurio
