### ISSUE TITLE
suggestion: a gen command

### ISSUE THREAD

**Issue by photoszzt** [ligurio/elle-cli#70]
Is it possible to create a gen command that generates a set of transaction history in json? The elle doc mentioned about this function but I'm not sure how to use it (I know lisp but I don't know anything about closure). It would be a great option to generate the sequence and feed it into unit test for db development.

**Comment by ligurio** [comment]
Hi! Perhaps you are talking about `elle.list-append/gen`. If so, it is a generator for list-append operations, generator is needed in a test, these operations then passed to a database client. `elle-cli` is a command line checker for histories that are result of testing by Jepsen. So the short anwser is: `elle-cli` does not need any generators provided by `elle`.

**Comment by photoszzt** [comment]
Yes, I am saying maybe this tool can also support the gen command which exposes the gen function’s args as command line arguments. Then its output can be piped to a file then use jet to convert to json or other formats.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ligurio** [comment]
And then what do you want to do with these artificial histories?

**Comment by photoszzt** [comment]
Use the history as a input to feed into the transaction system to validate that isolation is implemented correctly. Isn't that is one of the elle's proposed usage?

**Comment by ligurio** [comment]
> Use the history as a input to feed into the transaction system to validate that isolation is implemented correctly.
> Isn't that is one of the elle's proposed usage?

This is valid for `elle` library itself, but it is not a use case for `elle-cli`, because the main purpose of `elle-cli` is checking existed histories produced by tests in command-line mode.
