### ISSUE TITLE
Native binaries with GraalVM 

### ISSUE THREAD

**Issue by stevana** [ligurio/elle-cli#9]
Hi, have you considered using GraalVM to avoid the slow start up from and the dependency on JVM?

**Comment by ligurio** [comment]
@stevana Hi! Could you advise how to build binaries for GraalVM?

**Comment by ligurio** [comment]
https://github.com/clj-easy/graalvm-clojure/blob/master/doc/clojure-graalvm-native-binary.md

**Comment by stevana** [comment]
We did something similar using Elle over here: https://github.com/symbiont-io/detsys-testkit/tree/main/src/checker in particular the exact steps and flags are documented here: https://github.com/symbiont-io/detsys-testkit/blob/main/src/checker/default.nix#L20 .

**Comment by ligurio** [comment]
@stevana Sorry, I'm not interested in this. Feel free to send a patch via pull request.
